### ISSUE TITLE
Check and Bump lcobucci/jwt to version 5

### ISSUE THREAD

**Issue by dvesh3** [pimcore/personalization-bundle#11]
verify if we can bump to version https://github.com/lcobucci/jwt/releases/tag/5.0.0

**Comment by fashxp** [comment]
keep in mind not to introduce any BC breaks. 
Maybe we also can support ^4.0 || ^5.0 ?

**Comment by youwe-petervanderwal** [comment]
@dvesh3 @fashxp @markus-moser 
Can this issue be closed and version 1.1.0 be released so that we have a PHP 8.3 version available?

And after that, can https://github.com/pimcore/ecommerce-framework-bundle/pull/164 be finalized? Looks only to be an issue of missing version numbers
