### ISSUE TITLE
[Targeting] Error on Syfmony Profiler with pimcore targeting enabled

### ISSUE THREAD

**Issue by ogmdev** [pimcore/personalization-bundle#57]
The Symfony Profiler is broken when targeting is enabled.

![image](https://github.com/pimcore/personalization-bundle/assets/10164678/a8ccbd01-8f9a-4f36-ba80-76a77d226bf4)

In order to reproduce, install Pimcore Demo and activate Targeting. Then click on the Symfony Debug Bar. You should have a similar page.

**Comment by dvesh3** [comment]
Fixed by #58
