### ISSUE TITLE
composer requirement stops update to pimcore 11.1

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/personalization-bundle#59]
This bundle requires the pimcore/admin-ui-classic-bundle in version ^11.0.7 (current version 1.2.0) which requires pimcore in version ^11.0.7.

Is this bundle not compatible yet with the newer admin ui version or was the requirement set by mistake?

**Comment by aryaantony92** [comment]
@MercuryKojo This bundle is compatible with pimcore 11.1 and admin-ui-bundle 1.2. May I know, why do you think it stops updating to 11.1 ?
 It should update to pimcore 11.1 https://github.com/pimcore/personalization-bundle/blob/3efcf0a728bb71691239c32e1425fc9acc0646ca/composer.json#L15 and admin-ui-bundle 1.2https://github.com/pimcore/personalization-bundle/blob/3efcf0a728bb71691239c32e1425fc9acc0646ca/composer.json#L24 as per the composer requirements.

**Comment by MercuryKojo** [comment]
@aryaantony92 okay weird, thought that that was the reason my pimcore won't update
will check some more. I can close the issue if you want.

**Comment by aryaantony92** [comment]
Thanks for the reply. Sure, I think we can close this issue.
