### ISSUE TITLE
[Personalization] Overwrite area block with target group does not work

### ISSUE THREAD

**Issue by ogmdev** [pimcore/personalization-bundle#61]
This  behavior is only present in Pimcore 11 

## How to reproduce
1. On Pimcore demo website, open a CMS Document
2. Choose on target group
3. Overwrite an areablock
4. Remove it
5. Add a new areablock
6. Save.
7. Refresh the document. The new block is not present

## Why

In the post request to add a new areabrick, in field "realName" is missing prefix 'persona_XX-_'

You can see it on the screenshot below

![image](https://github.com/pimcore/personalization-bundle/assets/10164678/90501c0f-3bcc-4e01-8f87-ecde2d9a424b)

This appears since Personnalization moved to his own bundle (https://github.com/pimcore/pimcore/commit/d505e46b8b9ff9505e2fb1f1bcb0616321a3b8a8) 

We should probably update this Pimcore Core file to fix this 
https://github.com/pimcore/pimcore/blob/d505e46b8b9ff9505e2fb1f1bcb0616321a3b8a8/models/Document/Editable.php#L524

**Comment by dvesh3** [comment]
fixed by https://github.com/pimcore/pimcore/pull/16150
